"""add cloudinary_public_id to product_images

Revision ID: 5b8026f84a17
Revises: 0a2d0e2350a3
Create Date: 2026-08-11 17:59:36.487984

"""

from alembic import op
import sqlalchemy as sa


revision = "5b8026f84a17"
down_revision = "0a2d0e2350a3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_images", sa.Column("cloudinary_public_id", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product_images", "cloudinary_public_id")
    # ### end Alembic commands ###
