"""add email to orders

Revision ID: 752aebf4e8b2
Revises: b99505f54415
Create Date: 2026-08-11 22:25:40.625952

"""

from alembic import op
import sqlalchemy as sa


revision = "752aebf4e8b2"
down_revision = "b99505f54415"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("email", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "email")
    # ### end Alembic commands ###
