"""add is_admin to users

Revision ID: b99505f54415
Revises: 5b8026f84a17
Create Date: 2026-08-11 18:12:26.182636

"""
from alembic import op
import sqlalchemy as sa


revision = 'b99505f54415'
down_revision = '5b8026f84a17'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False,server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
